http:
  routers:
    hiregulf-http:
      middlewares:
        - redirect-to-https
      entryPoints:
        - http
      service: hiregulf
      rule: Host(`resume.endlessmaker.com`)
    hiregulf-https:
      entryPoints:
        - https
      service: hiregulf
      rule: Host(`resume.endlessmaker.com`)
      tls:
        certresolver: letsencrypt
  services:
    hiregulf:
      loadBalancer:
        servers:
          - url: "http://hiregulf-app:3000"
